### ISSUE TITLE
Make Neon as the default.

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#102]
Currently Luna is the default product of oasp4j to be installed.
Make Neon the default.

**Comment by maybeec** [comment]
Today I tried it out on linux by removing my /home/user/.eclipse configuration folder entirely and re-running the installer. However, Luna keep to be the default? Any glue why?
Is there any other caching going on? 

Btw. the installer was not reinstalled. But as far as I know, there is no cache within the eclipse-installer installation folder right?

**Comment by themetalone** [comment]
Does your redirection in the eclipse.ini point to the +dev_oomph+ branch?

**Comment by maybeec** [comment]
worked on dev_oomph branch. thanks.
