### ISSUE TITLE
Do not force to switch to advanced installation wizard

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#103]
We should keep the installation as easy as possible. So we should remove all the versions if this will force the user to switch to advance mode.
If this is not the cause for forcing the user to switch to advance mode, we should keep them. Maybe also the custom task installation is the cause for the question to switch. Can you investigate further @themetalone ?

**Comment by themetalone** [comment]
I'll make some further researches. But I think the Advanced Mode is forced by the 'non-generic' variables (e.g. the version numbers and even maybe the 'install.root') as well as by the additional tasks we need to install.

**Comment by themetalone** [comment]
After some trials I found that +installation.root+ also blocks the simple installer

**Comment by maybeec** [comment]
ok, what a pitty, but nevertheless. It is ok for me. Just a matter of taste.
