### ISSUE TITLE
Sonargraph model for OASP applications

### ISSUE THREAD

**Issue by tlueecke** [oasp/oasp4j-ide#125]
For those using Sonargraph to check their architecture we could use a generic sonargraph model for the Technical Architecture to be reused across the applications. In addition a sample for appliance to the restaurant application would be good.

Template should consist of a layering architecture file for OASP applications and a connection scheme for defining allowed inter-component dependencies. Demonstrate usage by appliance to the restaurant sample

**Comment by hohwille** [comment]
IMHO we can close this. We instead provide a separate plugin that can check the technical architecture with zero-config and the business-architecture just with a minimal config defining the dependencies of the business-components. This is way more efficient and lean. I would therefore close this.
