### ISSUE TITLE
Update to maven 3.5.2

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j-ide#128]
maven 3.5.0 is out with fixes and new feautres. We need to update our software package.

**Comment by hohwille** [comment]
`3.5.0` was broken: see https://issues.apache.org/jira/browse/MNG-6280
But with `3.5.2` everything works smooth for me now. I tested around 20 projects.
So IMHO ready for the next release.
Any complaints with `3.5.2`?

**Comment by maybeec** [comment]
@erikgruener can you provide a PR for that when working next on the oxygen upgrade anyhow?

**Comment by erikgruener** [comment]
We use m2e for the maven integration in eclipse and the following download is already the lastest release for oxygen: http://download.eclipse.org/technology/m2e/releases/1.8 

Is this what you were asking?  It does not state online if m2e 1.8 incldes maven 3.5.2

**Comment by erikgruener** [comment]
http://de-mucevolve02/files/oomph/resources/maven/ is updated

**Comment by maybeec** [comment]
Did you also update the profile to download this new maven version? Will you provide the PR for that?

**Comment by erikgruener** [comment]
The devon-Ide profile? yes i did and provided a PR

**Comment by maybeec** [comment]
this issue is on the oasp-ide.... ;) the devon-ide is a different one.

**Comment by maybeec** [comment]
adressed in #133
