### ISSUE TITLE
support for other platforms

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j-ide#15]
It would be nice to write unix/mac scripts for the bat files that we currently have for windows support. Contributions are very welcome.

**Comment by henning-cg** [comment]
I have started a basic port of the environment setup and workspace creation scripts at https://github.com/henning-cg/oasp4j-ide/tree/unix_support.

Right now, it only setups Maven and the necessary variables to get the eclipse config generator running.

Right now I am following the same structure, more or less, than the windows version, so future changes are more portable between the two.

Instead of a console.bat there is a env.sh, which one should source from a bash prompt to set up the necessary variables.

Any further input is very welcome!

**Comment by hohwille** [comment]
Cool! @henning-cg Thanks for your input. :+1: 
We will integrate this into the next release (Probably we should rename to 1.4.0 then).

**Comment by hohwille** [comment]
Would you mind to merge this onto develop and create a pull-request for it?

**Comment by hohwille** [comment]
> Instead of a console.bat there is a env.sh, which one should source from a bash prompt to set up the necessary variables.

IMHO there would be no need for setting OASP_PROJECT_HOME externally.
You could use "dirname $0" to figure out the location relative from the script.

**Comment by henning-cg** [comment]
"dirname $0" does not work if you source a script, ie. execute it directly in the running shell, as $0 would point to the executable of the running shell.

I think there is vale in determining the absolute path to the active project's folder, as it makes writing other scripts easier, as long as you have sourced env.sh beforehand.

**Comment by henning-cg** [comment]
Created pull request #48

**Comment by hohwille** [comment]
> "dirname $0" does not work if you source a script...

I am aware, but I was not talking about env.sh but about ```environment-project.sh```.
Maybe I will find some time on the long weekend to give it a try on my linux machine and find a solution.
Thank you so much for your input!

**Comment by henning-cg** [comment]
Ah, I see.

Well, as I saw it, env.sh is the main starting point, and every other script depends on having sourced env.sh earlier, including environment-project.sh, but it is true that the other scripts are meant to be called directly, and not sourced, and therefore could simply use $0.

_________________________________________________________

Henning Kiel | Capgemini Spain | Valencia
Senior Consultant | Technology Services | Dpto. Arquitectura de Software
Tel.: +34 96 104 (1848) | Mov.: +34 646 714 996 | henning.kiel@capgemini.com<mailto:henning.kiel@capgemini.com>
Avda. del Marqués de Sotelo, 6 (46002) Valencia - Spain
_________________________________________________________
________________________________

**Comment by henning-cg** [comment]
Should we close this issue and create another one for adding a platform-flag to the workspace configuration?

**Comment by hohwille** [comment]
Created #53 and #54. This one is done now.
