### ISSUE TITLE
Change SVN TeamProvider

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#31]
Currently two SVN TeamProvider are pre-installed in the current Client-PE release: SVNKit & JavaHL Native.
As JavaHL Native seems to be more instable than SVNKit, we should uninstall JavaHL Native or at least set SVNKit to the new default TeamProvider.
Nevertheless, I have some observations on that:
After uninstalling JavaHL Native from my local Client-PE instance, I got further errors, e.g. while committing, which seems occur in the JavaHL Native namespace. Possibly, we should have a look at a fresh install, where no JavaHL TeamProvider has been installed before to test, whether the errors might caused by a JavaHL installation.

**Comment by hohwille** [comment]
Simon confirmed that JavaHL is the default and caused a lot of pain and trouble (Previous operation has not finished; run 'cleanup' if it was interrupted). He also confirmed that changing to SVNKit resolved the problem for him.

This means we either have to remove JavaHL entirely from our eclipse distro or we have to ensure that the default is set to SVNKit and NOT to JavaHL.

**Comment by may-bee** [comment]
I think we can close this issue, can we?
Has it also already been fixed in release 1.3.0?

**Comment by hohwille** [comment]
done (for fresh workspaces it will now be initialized properly if latest settings are used)
