### ISSUE TITLE
Vote for default set console buffer to maximum valid size

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#32]
I vote for setting the console buffer size to the maximum allowed size.
Especially for large console logs like caused by spring, you might go back further than the current default configuration of the console allows.

**Comment by hohwille** [comment]
good suggestion to increase the default. Should we use 800000 or 1000000 or disable limit at all? Removing the limit at all used to cause some performance issues and heap/GC pain according to my experience. However, I did not see this problem again in the past. Is that an effect of newer JVM architecture or has luna solve the problem?

**Comment by may-bee** [comment]
> However, I did not see this problem again in the past. Is that an effect of newer JVM architecture or has luna solve the problem?

I always adjust the value to 1000000 in my installations and have not observed any issues with that. I have never removed the limit entirely, so neither any experiences nor any problem analytics from my side according to that.

**Comment by hohwille** [comment]
fixed (wrong issue ref in commit msg): 
https://github.com/oasp/oasp4j/commit/b1ecf0354d13dc590ad188be28c5972e17993b17
