### ISSUE TITLE
Integrate StartExplorer Plugin with IDE infrastructure scripts

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#33]
It would be very nice if we could manage to integrate the StartExplorer Plug-in with the IDE's initialization scripts. Thus we would be able to start an IDE initialized command line using shortcuts of StartExplorer directly out of eclipse.

I had a short look at this and saw a lot of freedom for customization StartExplorer gives advanced users. To maybe it is worth to have a look at in the near future.

**Comment by hohwille** [comment]
I was also thinking about this but had no idea so far how to achieve this. I will have a look. Suggestions are most welcome...

**Comment by may-bee** [comment]
**The following configuraiton will do the trick**
Nevertheless, providing this configuration as default preferences has two issues we have to discuss.

1. Enabling the configuration below, StartExplorer is statically configured to work on Windows.
2. The IDEenv.bat script should have been registered in the registry. I have not tested yet, what StartExplorer will do if the script has not been registered.

_File:_
`\workspaces\trunk\.metadata\.plugins\org.eclipse.core.runtime\.settings\de.bastiankrol.startexplorer.prefs`

_File-Content:_
```
de.bastiankrol.startexplorer.auto_detect_desktop_environment=false
de.bastiankrol.startexplorer.copy_resource_path_separator_custom_string=, 
de.bastiankrol.startexplorer.copy_resource_path_separator_standard=\n
de.bastiankrol.startexplorer.custom_desktop_environment_command_start_file_manager=explorer.exe /e,${resource_path}
de.bastiankrol.startexplorer.custom_desktop_environment_command_start_file_manager_and_select_file=explorer.exe /select,${resource_path}
de.bastiankrol.startexplorer.custom_desktop_environment_command_start_shell=cmd /c start cmd /s "/k pushd ${resource_path} & IDEenv"
de.bastiankrol.startexplorer.custom_desktop_environment_command_start_system_application=cmd.exe /c ${resource_path}
de.bastiankrol.startexplorer.custom_desktop_environment_working_directory_mode_custom_commands=NONE
de.bastiankrol.startexplorer.custom_desktop_environment_working_directory_mode_start_file_manager=NONE
de.bastiankrol.startexplorer.custom_desktop_environment_working_directory_mode_start_shell=NONE
de.bastiankrol.startexplorer.custom_desktop_environment_working_directory_mode_start_system_application=NONE
de.bastiankrol.startexplorer.selected_desktop_environment=WINDOWS
de.bastiankrol.startexplorer.use_custom_desktop_environment=true
eclipse.preferences.version=1
```

**Comment by hohwille** [comment]
Cool. Thanks for the investigation :+1: 
I will check and integrate into the next release...

**Comment by hohwille** [comment]
Works like a charm...
