### ISSUE TITLE
IDE blocks deletion of non-java resources

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#36]
Some other collegues as well as myself observe a blocking behavior when deleting non-java resources after have opened them beforehand.
In addition the same behavior occurs when trying to rename a non-java resource like a xml file.

Can someone else confirm this strange behavior?
Possibly it has been solved in the 1.3.0 release. I have to check this...

**Comment by hohwille** [comment]
I retested with the recent release and can not reproduce the problem. IMHO this is more of a bug in eclipse or related plugins. Maybe you have added additional plugins yourself.
I give it some time before closing but consider this as done...

**Comment by may-bee** [comment]
I updated my ide to the 1.3.0 release without installing any additional plug-ins.
As an example: After starting the tomcat and stopping it again, I cannot rename log4j.properties any more.

**Comment by may-bee** [comment]
Now I an error while deleting a html file...

**Comment by hohwille** [comment]
I am very sure that this has nothing to do with oasp4j-ide itself but with Eclipse. However, we need to track down the problem and find a solution to all who are struggling with this problem.

**Comment by hohwille** [comment]
Is this related to Windows file locking (e.g. when it comes to tomcat start/stop)?

**Comment by hohwille** [comment]
Can you check if you can rename the same file in Windows-Explorer without problems?

**Comment by hohwille** [comment]
Is this problem probably related to SVNKit? I am using GIT as team provider and renaming/deletion operations are actually processed via Team provider.

**Comment by 7Bit** [comment]
We have experienced similar issues since we are using the oasp4j-ide (v1.1.0). If we import a multi-module Maven project, even the target folders can't be cleaned often. You have to restart the IDE in order to compile again.

This does not happen if you only import all child modules of a multi module build. Unfortunately you can't easily edit the parent POM, that's the downside of this workaround.

**Comment by hohwille** [comment]
> If we import a multi-module Maven project, even the target folders can't be cleaned often. You have to restart the IDE in order to compile again.

Please follow OASP best-practice:
https://github.com/oasp/oasp4j/blob/develop/pom.xml#L444

**Comment by hohwille** [comment]
> This does not happen if you only import all child modules of a multi module build. Unfortunately you can't easily edit the parent POM, that's the downside of this workaround.

Eclipse in general is pain for multi-module projects. Other IDEs can handle this a lot better. If you import all projects and search for a resources you will find multitudes of occurences for the same file. (parent/module/src/main/resources/file, parent/module/target/classes/file, module/src/main/resources/file, module/target/classes/file, etc.).

**Comment by hohwille** [comment]
As I already commented I think the problems you are actually facing with dead-locks and stalls is not at all related with oasp4j-ide but with subclipse and subversion integration (both via javahl and SVNKit - each has its own problems). Maybe you need to try downgrading subclipse. This is not a new situation. Subclipse hat several releases that were practically not usable in production. We need to learn that changes to subclipse need to be tested by real live projects using SVN. As oasp is using GIT we missed this problems. Sorry for that.

**Comment by hohwille** [comment]
Eclipse is free and for free you get a great IDE after all. We have to be aware that Java8 support and related stuff was a massive amount of effort and complexity. On the other hand Eclipse lacks improvements and progress on fundamental things such as formatter or stability problems as this issue. We can not ignore these problems on the long run as you can see by websites like this:
http://www.ihateeclipse.com/

I do not want to blame or flame the eclipse community. The people active there are doing a good job but there are millions of users complaining and too little contributors actually improving. One problem might be that Eclipse itself is over-engineered and it is very complex for newbies to get started in order to provide even a trivial improvement.

**Comment by hohwille** [comment]
@7Bit and @may-bee: any update on this? Did you manage to create a new eclipse distro for your software-package and resolve the issue. This is a problem of Eclipse in combination with subclipse and has nothing to do with oasp4j-ide itself. I would like to ensure that we have a stable software package and then close this issue.

**Comment by may-bee** [comment]
No new new about that. As analyzed in my previous post, eclipse gets more and more crap for SVN users. I created a new clean software package for our project, but the problem persists if you run eclipse long enough renaming non java resources...

**Comment by hohwille** [comment]
@may-bee that is sad to hear. However, we will still have the need for SVN support for a while. Should we consider to switch to subversive instead of subclipse?

**Comment by hohwille** [comment]
Can someone strongly affected by this try to uninstall CobiGen Plugin from Eclipse and let us know if that makes any differend (see devonfw/tools-cobigen#122)?

**Comment by lgoerlach** [comment]
I had the same problem.

I reproduced the bug using these steps:
* Created .ftl file, opened it in Eclipse (with CobiGen installed), closed it, couldn't delete.
* Uninstalled CobiGen-Plugin, restarted Eclipse, opened .ftl, closed it, could delete.
* Installed CobiGen again, restarted Eclipse, couldn't delete the .flt even without having opened and closed it beforehand.

(might be interesting for https://github.com/devonfw/tools-cobigen/issues/122, too)

**Comment by hohwille** [comment]
@lgoerlach thanks for testing. 
So not an oasp4j-ide issue and even does not seem to be the problem of subclipse.
