### ISSUE TITLE
createOrUpdateWorkspaces does not work with whitespaces in path

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#38]
createOrUpdateWorkspaces seems to have problems when whitespaces are part of the path to the ide root folder.

**Comment by hohwille** [comment]
This is not only about createOrUpdateWorkspaces. That is why we wrote: 

> Create the project directory as a new directory of your choice for your project. Avoid long paths and white spaces to prevent trouble.

https://github.com/oasp/oasp4j-ide/wiki/guide-usage

**Comment by hohwille** [comment]
We can improve the script as possible but also m2e will not work if you use whitespaces in your path and that is out of our scope to fix.

**Comment by may-bee** [comment]
ok, yes thats true.
I was observing this while creating a tmp folder for upgrading our project ide.
So no matter, than this will be convention. Thats fine.
