### ISSUE TITLE
Provide xml launch config for Tomcat

### ISSUE THREAD

**Issue by julianmetzler** [oasp/oasp4j-ide#40]
From issue [#183](https://github.com/oasp/oasp4j/issues/183) of oasp4j we have the issue to provide a launch config to use a reasonable working directory in order to use the same relative path for logging (configured in logback.xml) in Tomcat and in Eclipse.

**Comment by julianmetzler** [comment]
Putting a xml launch config into the project setting directory for the Tomcat settings works (oasp4j\settings\eclipse\workspace\setup\Servers\Tomcat7-config).
I don't know if this is the right or best place for such a configuration.

The problem is the saved launch config contains absolute paths like *C:/projects/oasp/software/Tomcat/bin/bootstrap.jar*.

**Comment by hohwille** [comment]
The path should IMHO only be oasp4j\settings\eclipse\workspace\setup\Servers so eclipse will automatically find and register it.
Oasp4j-ide provides variable substitution to prevent absolute paths. look at other XML or pref files and search for ${...} in there.

**Comment by hohwille** [comment]
The logging directory is now configurable and this is not needed anymore.
