### ISSUE TITLE
secure configuration (OWASP A5)

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j-ide#44]
As we are providing template configurations for e.g. tomcat we also have to consider security aspects such as:
https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration

**Comment by hohwille** [comment]
Anything left to do? Or can we close this?

**Comment by may-bee** [comment]
:+1: close

**Comment by hohwille** [comment]
jep. it is just a developers instance. We could add custom error pages to prevent tomcat version exposure there but that is more a production that a development env issue.
