### ISSUE TITLE
Several issues while upgrading to 1.4.0-rc1

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#51]
I recently upgraded my oasp4j-ide to 1.4.0-rc1 to be able to work with js projects and by the way test the new rc.
I observed two issues so far:

1. I could not start eclipse until I removed `-javaagent:lombok.jar` from the eclipse.ini
2. Furthermore, eclipse could not load the workspace with the existing .metadata created by the previous release, which is quite annoying.

**Comment by lgoerlach** [comment]
Indeed, that sounds really annoying. I assembled the IDE on an almost completely clean OS, maybe that's the reason I didn't encounter such issues.

For Lombok, you could try executing the lombok.jar in the Eclipse directory and use its installer. They claim that all it does is adding said line to the eclipse.ini, but who knows?

Regarding .metadata: Eclipse is a beast in many ways and the plugin handling is one of them. I suppose that one of the plugins might be incompatible with the old version of its config. I don't know if it's feasible to find out which one it is, furthermore such problems might recur every time the plugin configuration is changed. But it does work if the projects from the old workspace are imported into a new one, doesn't it?

**Comment by hohwille** [comment]
Thanks for your feedback.
Indeed there was a bug in eclipse.ini missing this line:

    -Xbootclasspath/a:lombok.jar

Maybe lombok messed something up here with the installer GUI. However, easy one - fixed.

The messed workspace issue is servere but I can not reproduce it. I used multiple projects where I upgraded to 1.4.0-rc2 and it works fine (with the above lombok fix). The previous workspace is recovered properly by the new eclipse.
Was your old workspace created with eclipse before luna? We just upgraded to luna SR2.
I do not expect that the workspace got incompatible and will be messed up. That would be a huge problem then...

**Comment by hohwille** [comment]
BTW: I also removed a folder named ```${M2_REPO}``` located in ```software/eclipse```.

**Comment by may-bee** [comment]
>  Was your old workspace created with eclipse before luna? We just upgraded to luna SR2.

No, I upgraded from the latest oasp-ide release (1.3.1). I have the workspace at hand. Restoring it will break the workspace initialization and thus starting eclipse is not possible.
If I am the only one observing this behavior, it might be not that problematic. But we should take care of it.

I now added manually the line stated above to my eclipse.ini such that I can see two lombok related lines:

```
-javaagent:lombok.jar
-Xbootclasspath/a:lombok.jar
```

Even with this configuration, I cannot start eclipse. I immediately get the following dump:

![oasp4j-ide-1 4-rc-bug](https://cloud.githubusercontent.com/assets/1427255/7724225/f4ea8cfa-feef-11e4-98c8-56f92f9b4b2e.PNG)

**Comment by hohwille** [comment]
Strange. Why does this not happen to me. We need to investigate what is going on here.
However, I also start to doubt about Luna SR2. It seems actually to be even worse that the previous version we used before. My entire perspective is now messed up and also my Eclipse log is so full of event loop and other exceptions. I am loosing trust that Eclipse will ever get stable again.

**Comment by may-bee** [comment]
The problems might be also caused by the large bunch of plugins added in this release, e.g. for JavaScript support and similar.

**Comment by hohwille** [comment]
JS support (angularJS plugin) was added in rc2 that I am using.
I am trying to uninstall it and see if that has any effect.
Howevere, in the logs I am seeing massive occurrences of this bug that is claimed to be fixed in 4.4.M7 that we are far beyond:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=430024

**Comment by hohwille** [comment]
Once again I was facing the slf4j error bring various plugins like m2e down. I will drop SonarQube plugin until they have seriously solved that issue.
Further I discovered that STS/spring ide is replacing various views like properties view or m2e POM view and XML view with own extensions. These also ran into bugs and brought the entire Eclipse down. After removing this I now have a working IDE as it seems. Will do more testing to better track down the errors. Maybe just uninstalling SonarQube plugin will solve most issues, needs more testing. Good that we now have this feedback and testing before we officially do releases.
With the original release I sometimes had ~40 event loop exceptions per second bringing the entire eclipse down and spamming the log.

**Comment by may-bee** [comment]
:+1: will you create a rc2 to be sure, that we test the same eclipse configuration?

**Comment by henning-cg** [comment]
Is this still an issue with the rc2?

**Comment by may-bee** [comment]
seems to be fixed in rc2
