### ISSUE TITLE
Integrate Quick Search

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#6]
It would be nice to integrate "Quick Search for Eclipse 3.6.1.RELEASE " (http://marketplace.eclipse.org/content/quick-search-eclipse)

This plug-in is a very helpful and fast search tool. I am using it each 5 minutes and it improves my productivity tremendously. You can open the quick search dialog by Ctrl+Shift L

**Comment by may-bee** [comment]
What about this ticket?
I have a clean ide 1.3.0 and installed QuickSearch.
No problem. Possibly we can integrate QuickSearch in the next release again?

**Comment by hohwille** [comment]
If #13 is also fixed with recent versions of the plugins that is fine and I will give it another try.
But give me some time as I am busy at the moment...

**Comment by lgoerlach** [comment]
Issue fixed in release candidate 1.4.0
