### ISSUE TITLE
1.4.0-rc2 invalid update sites

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#61]
There are two issues with the update sites preconfigured in the rc2:

1. codehaus update sites are no longer available, which annoys you with login requests...
![update site error](https://cloud.githubusercontent.com/assets/1427255/8351964/81040eac-1b31-11e5-9c09-7aa961620115.PNG)

2. CobiGen update site should point to `jar:file:////de-file10/ClientPE/OASP/CobiGenerator/Releases/stable/cobigen-eclipse.zip!/` instead of your local path ;)

**Comment by lgoerlach** [comment]
The new update site for sonar-ide is http://downloads.sonarsource.com/eclipse/eclipse/.
We should alter the paths at least for the next RC...

**Comment by henning-cg** [comment]
Would be nice to have another solution for the cobigen update site.

de-file10 is not accesible, at least for us here in Spain.

Although I'm not sure how to solve it in a secure way.

**Comment by henning-cg** [comment]
Would be nice to have another solution for the cobigen update site.

de-file10 is not accesible, at least for us here in Spain.

Although I'm not sure how to solve it in a secure way.

_________________________________________________________

Henning Kiel
Senior Consultant 2 | Custom Software Development | Application Services

Capgemini Spain | Valencia
Tel.: +34 96 104 (1848) | Mob.: +34 646 714 996
www.capgemini.com

Avda. del Marqués de Sotelo, 6 (46002) Valencia - Spain

People matter, results count.
_________________________________________________________
________________________________

**Comment by may-bee** [comment]
Ah ok, I missed that point. Then we should remove the cobigen update site entirely from the provided ones. Otherwise you will get errors on updating or installing any plug-in that the update site is not available as it points to an invalid local location.

You are right, it would be nice to have a different solution. Nevertheless, I currently cannot imagine of any different besides a globally accessible network share as we also cannot deploy it on github due to the access restrictions on devonfw.

**Comment by hohwille** [comment]
Thanks for giving notice. We will take care of this for 1.4.0. Also the software package documentation should contain this as a reminder so we do not get such things again in later releases.

**Comment by hohwille** [comment]
Done
