### ISSUE TITLE
Upgrade to Eclipse Mars release

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#62]
Upgrade software-package to eclipse mars, which will enable e.g. #9

**Comment by hohwille** [comment]
We are working on this. However most eclipse major releases introduced trouble and we usable after the first or second SR release. We will see that. Quality processes at eclipse have improved. We will see...

**Comment by hohwille** [comment]
To my surprise the entire installation of Mars including all our additional plugins caused no error so far.
However, we need to test this properly before we can go for Mars.

**Comment by hohwille** [comment]
As this looks really promising and I am already working with Mars now and do not have problems, I will already provide it via rc3 today and plan this for 1.4.0.

**Comment by hohwille** [comment]
Looks good. We can reopen in case we get in trouble and have to revert.

**Comment by hohwille** [comment]
I knew there will be bugs:

E.g. generating trivial getter/setters stopped working with this error:
![eclipsemarsegenerategettersetter](https://cloud.githubusercontent.com/assets/1923119/8477663/36e03cba-20cc-11e5-8069-8e122273259e.png)

**Comment by may-bee** [comment]
lovely :+1: 
I think there are neither basic tests nor smoke tests for eclipse covering such basic features.

**Comment by hohwille** [comment]
And here is my next finding with Mars (do some undo with [ctrl][z] and then save with [ctrl][s]):

![eclipsemarssavefailed](https://cloud.githubusercontent.com/assets/1923119/8507245/68e30494-223a-11e5-91ae-81d0fb8fe908.png)

**Comment by hohwille** [comment]
Also as with almost every Eclipse major release the performance went down. You really notice this while typing when Mars often stalls and the entire UI freezes for a while.

**Comment by hohwille** [comment]
And another one: I cannot launch anything. Eclipse continuously schedules a build that stops immediately. This is causing a kind of infinity loop. You can wait for hours...

![eclipsemarsendlessbuildcannotlaunch](https://cloud.githubusercontent.com/assets/1923119/8598813/3b6604cc-265d-11e5-9997-6f6dde2c5785.png)

**Comment by hohwille** [comment]
So we officially have to wait at least till September:
https://wiki.eclipse.org/Mars/Simultaneous_Release_Plan#SR1
:-1:

**Comment by hohwille** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=472205

**Comment by may-bee** [comment]
nice... 
> Keeping this bug open for >eventual< backport to 4.5.1.

They just released a new version of eclipse and do not even force bugs to be fixed in the maintenance releases.

**Comment by hohwille** [comment]
If I open an SQL file then in most cases the view breaks and also causes other views like package explorer to get empty and broken. In such case you have to restart Eclipse.
IMHO Mars ist still not usable for productive development.

**Comment by hohwille** [comment]
Index error for getter/setter generation has been fixed meanwhile but same error still remains when refactoring anonymous to nested class.

**Comment by hohwille** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=462945

Has been fixed but still not available if you install all latest updates the error is still there.

**Comment by hohwille** [comment]
Also Cleanup is causing the IndexOutOfBoundsException. Sorry to say again:
Quality of Eclipse IDE is a big pain.

**Comment by hohwille** [comment]
Also the Java source code formatter does not work properly. Often formatting does nothing.
Mars is out now for about five month now and also SR1 is available since a longer while.
However, the entire Mars IDE for Java is still so buggy that it can not be used in productive development.

**Comment by hohwille** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=386648

**Comment by hohwille** [comment]
So after all the shit-storm about Eclipse I also have to apologize: The bugs with getter/setter generation and related stuff have really been fixed in Mars SR1. The problem was that installing other plugins caused Eclipse to downgrade (!) JDK plugins so the bugs came back. So in the end for this the update mechanism is to blame and not JDK.
After all, good that Eclipse is making progress and gets usable for productive development again...
Still lots to improve...

**Comment by maybeec** [comment]
This is obsolete, isn't it? The software package will be released independently in the current state.

**Comment by hohwille** [comment]
We had Mars rolled out already a long time ago. Next is to go for Neon.
