### ISSUE TITLE
Integrate FreeMarker IDE

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#63]
The new release of JBoss Tools also updated the FreeMarker IDE to match one of the latest releases of the FreeMarker engine. http://tools.jboss.org/documentation/whatsnew/jbosstools/4.3.0.Beta1.html#freemarker
We should make an evaluation how stable this plug-in now is and whether we want to integrate it to have some more support while editing generator templates.

**Comment by hohwille** [comment]
I assume that you already installed this into your Eclipse and will give us feedback. I will also give it a try. But after all the trouble I have seen with Eclipse plugins I will not suggest to include it into 1.4.0 that should come out very soon.

**Comment by maybeec** [comment]
too buggy, we should ignore this.
