### ISSUE TITLE
Nodejs for x86 systems

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#69]
It seems, that nodejs has been upgraded to a x64 version silently.
The current version does not work on x86 systems. This is not acceptable as there are several guys out there strugling with their x86 systems.

**Comment by hohwille** [comment]
Thanks for the feedback. I was not aware of this. This only happened in RC versions? Or already in 1.3.0? I will fix this for 1.4.0.

**Comment by may-bee** [comment]
It is just the case for the latest devon release.
We should fix this as fast as possible to provide a consistent distribution zip for the upcoming schools.

**Comment by hohwille** [comment]
We consider this for 1.4.0. Was already fixed in RC versions.
