### ISSUE TITLE
create first oomph setup 

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#83]
This issue encloses the development of the first Oomph profile to install the OASP4J.
Deploy it in an installer which forks Oomph developed on themetalone/oomph-fork#2.
- [x] disable launch automatically by default
- [x] disable use bundle pool by default
- [x] disable eclipse catalogs by default
- [x] enable oasp4j catalog by default

**Comment by themetalone** [comment]
Is there a dedicated location where I can upload the installer?

**Comment by maybeec** [comment]
For now, please add it as a release to your oomph fork and deploy it to the created GitHub release. You may post the link here for now.

**Comment by themetalone** [comment]
https://github.com/themetalone/oomph-fork/releases/tag/v1.5.0.c.1
