### ISSUE TITLE
Strong recommendation of upgrading m2e to 1.6

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j-ide#9]
There is a bug in the current version of m2e, which is really annoying, when retrieving your code artifacts with m2e:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=440273

Version 1.6 containing the Bugfix is [not yet released](http://wiki.eclipse.org/M2E_updatesite_and_gittags#m2e_releases), but as far as I got the hint in the ticket and [release plan of Eclipse Mars](http://wiki.eclipse.org/Mars/Simultaneous_Release_Plan) right, it should be released at 3rd of october.

**Comment by lgoerlach** [comment]
There is still no official release for version 1.6, but I will test it locally for a few days from now on!

**Comment by may-bee** [comment]
You may want to try the milestone build (http://download.eclipse.org/technology/m2e/milestones/1.6/).
It is worth a try. As stated by one of the developers, it should work and users also confirms this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=440273

**Comment by lgoerlach** [comment]
That's exactly the one I used. I upgraded Maven to this milestone build in my IDE (RC 1.4.0). 
Unfortunately, it still shows an error while building the workspace (the Maven plugin can't be loaded):
![error message](https://cloud.githubusercontent.com/assets/12272186/7509995/cf037b58-f497-11e4-9e27-bfe5ba2b7205.png)
I tried it with a fresh workspace, too. Everytime the plugin shall be activated, it cannot load. Apparently, that upgrade crashed the whole Maven configuration (the error persists after I reverted to version 1.5).

I will try it with RC 1.4.0 one more time (by uninstalling m2e 1.5 completely before installing 1.6) and report back after that.

**Comment by lgoerlach** [comment]
Okay, that didn't help...
I suggest we try it again when someone builds the software package with a clean Eclipse the next time. Maybe m2e 1.5 configured too many things irreversibly, thus causing the m2e 1.6 crash.

**Comment by may-bee** [comment]
what a pitty, then we have to wait until the Mars release...

**Comment by hohwille** [comment]
1.4.0 will be shipped with Mars.
