### ISSUE TITLE
deploy first release of linux-scripts

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#92]
Linux scripts should be deployed once on maven central to enable a stable Oomph build.

**Comment by themetalone** [comment]
@maybeec could you provide more details about what I should do here?

**Comment by maybeec** [comment]
This has to be done by @hohwille due to code signing.
@hohwille correct me if I am wrong. @PriyankaBelorkar is currently working on finalizing the linux scripts to support the same functionality as the windows script do. However, I would strongly recommend to have a snapshot release of the linux-scripts already available and release the linux scripts as soon as possible as we are highly dependent on them with the Oomph build, which is in testing phase already.

**Comment by maybeec** [comment]
relates to #66

**Comment by hohwille** [comment]
more or less a duplicate of #66. Will be part of 1.4.0.
